apiVersion: v1
kind: Secret
metadata:
  name: knp-connect-secret
type: Opaque
stringData:
  SECRET_KEY: "change-me"
  S3_ACCESS_KEY_ID: "minioadmin"
  S3_SECRET_ACCESS_KEY: "minioadmin"
  GOOGLE_CLIENT_ID: ""
  SMTP_HOST: ""
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SMTP_FROM_EMAIL: "no-reply@example.com"
